name: elementary-transformations-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Base environment dependencies
  - python=3.11
  - ipykernel
  - notebook
  - pandas
  - numpy
  - h5py
  - loguru
  - pyyaml
  - matplotlib
  - scipy
  - imageio
  - imageio-ffmpeg
  # Development tools
  - conda-lock>=2.0.0
  - pre-commit
  - pip
  - pip:
      - opencv-python
  - pytest
  - pytest-cov
  - black
  - isort
  - ruff
  - flake8
  - mypy
  - types-PyYAML
  - types-requests
  - types-python-dateutil
  - types-pytz
  - types-six
