name: elementary-transformations
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - notebook
  - pandas
  - numpy
  - h5py
  - loguru
  - pyyaml
  - pytest
  - matplotlib
  - scipy
  - ruff
  - imageio
  - imageio-ffmpeg
  - pip
  - pip:
      - opencv-python
