name: elementary-transformations
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - h5py
  - loguru
  - pyyaml
  - pytest
  - matplotlib
  - scipy
  - ruff
  - imageio
  - imageio-ffmpeg
  - opencv-python
