name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dev-env
          environment-file: dev-environment.yml
          auto-activate-base: false
      - name: Install additional dependencies
        run: |
          conda install -y -n dev-env opencv imageio
      - name: Run pre-commit
        run: |
          conda run -n dev-env pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Run pytest
        run: |
          conda run -n dev-env pytest -v
